spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/centrifugo
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    security:
      user:
        name: admin
        password: admin



centrifugo:
  api-key: d7627bb6-2292-4911-82e1-615c0ed3eebb
  channel1: save
  channel2: channel2
  channel3: channel3
#  deviceSummary: device-stat
  channel4: something2
  method: publish
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiItaCIsImV4cCI6MTcyMTQwMjYyNCwiaWF0IjoxNzIwNzk3ODI0fQ.IeQG7hUifXhHaH7yUBukCAJ_iexfstR83w25kNwqMQE
  url: http://localhost:8000
  websocket: ws://localhost:8000/connection/websocket
#  wss://smpp.stlghana.com/connection/websocket
